using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;
using Random = UnityEngine.Random;

public enum PanelType
{
    fire,
    light,
    water,
    grass,
    heart
}

public class GameManager : MonoBehaviour
{
    public static GameManager instance;

    [Header("Panel")]
    public Panel panel;
    private List<Panel> nearPanels = new();
    private List<List<Panel>> chainSequence = new();
    private List<Panel> panelGarbage = new(); //ШФУГИЎПы
    private Dictionary<Panel, PanelType> panels = new();
    public int maxPanelCount = 30;

    private void Awake()
    {
        if(instance == null)
        {
            instance = this;
        }
        Application.targetFrameRate = 60;
    }

    private void Start()
    {
        StartCoroutine(PanelDrop());
    }

    private void Update()
    {
        Click();
    }

    IEnumerator PanelDrop()
    {
        while (true)
        {
            if(panels.Count == maxPanelCount)
            {
                StopCoroutine(PanelDrop());
            }
            else
            {
                CreatePanel();
            }
            yield return new WaitForSeconds(0.05f);
        }
    }

    //ЦаГЮРЛ Л§МКЧЯДТ БтДЩ
    private void CreatePanel()
    {
        Panel newPanel = Instantiate(panel);
        int rand = Random.Range(0, 5);
        newPanel.SetSprite(rand);
        newPanel.SetTypes(rand);
        panels.Add(newPanel, newPanel.panelTypes); //Л§МКЕШ ЦаГЮЕщРЛ ИЎНКЦЎПЁ ДуБт
    }

    private void Click()
    {
        if (Input.GetMouseButtonDown(0))
        {
            RaycastHit2D ray = Physics2D.GetRayIntersection(Camera.main.ScreenPointToRay(Input.mousePosition));
            if (ray.transform.CompareTag("Panel"))
            {
                Panel p = ray.transform.GetComponent<Panel>();
                if (p != null) {
                    nearPanels = GetNearPanel(p, SameColor(p), new List<Panel>());
                    SortChainSequence();
                    RemoveChainSequence();
                }
            }
        }
    }

    private List<Panel> SameColor(Panel clickedPanel)
    {
        //ААРК ХИРдРЧ ЦаГЮГЂИЎ И№РК ЦаГЮ ИЎНКЦЎ Л§МК
        List<Panel> sameColor = new();
        foreach (var panel in GameManager.instance.panels)
        {
            PanelType kvalue = panel.Value;
            if (GameManager.instance.panels.TryGetValue(clickedPanel, out PanelType value) && kvalue == value)
            {
                sameColor.Add(panel.Key);
            }
        }
        return sameColor;
    }


    private void SortChainSequence()
    {
        if (nearPanels.Count == 0) return;
        chainSequence.Clear();

        Queue<Panel> queue = new();
        HashSet<Panel> visitPanel = new(); //СпКЙ ШЎРЮ

        Panel startPanel = nearPanels[0];
        
        queue.Enqueue(startPanel);
        visitPanel.Add(startPanel);

        while (queue.Count > 0)
        {
            int panelCount = queue.Count;
            List<Panel> currentPanelList = new();

            for(int i = 0; i < panelCount; i++)
            {
                Panel currentPanel = queue.Dequeue();
                currentPanelList.Add(currentPanel);

                foreach (Panel near in GetNextPanel(currentPanel))
                {
                    if (!visitPanel.Contains(near))
                    {
                        visitPanel.Add(near);
                        queue.Enqueue(near);
                    }
                }
            }
            chainSequence.Add(currentPanelList);
        }
    }

    private void RemoveChainSequence()
    {
        if(chainSequence.Count > 0)
        {
            List<Panel> list = chainSequence[0];
            chainSequence.RemoveAt(0);
            foreach(Panel obj in list)
            {
                obj.BrokenPanel();
                panelGarbage.Add(obj);
            }
            Invoke("RemoveChainSequence", 0.2f);
        }
        else
        {
            DestroyPanel();
        }
    }

    private void DestroyPanel()
    {
        foreach(Panel obj in panelGarbage)
        {
            panels.Remove(obj);
            obj.BreakPanel();
        }
        panelGarbage.Clear();
    }

    //АЁБюПю ЦаГЮ ЙнШЏ
    private List<Panel> GetNextPanel(Panel obj)
    {
        List<Panel> list = new List<Panel>();
        foreach (Panel obj2 in nearPanels)
        {
            if (FindNearPanel(obj, obj2)) list.Add(obj2);
        }
        return list;
    }

    //АЁБюПю РќУМ ЦаГЮ ИЎНКЦЎ ЙнШЏ
    private List<Panel> GetNearPanel(Panel p, List<Panel> sameList, List<Panel> sortedList)
    {
        sortedList.Add(p);
        foreach (Panel panel in sameList)
        {
            if (!sortedList.Contains(panel) && FindNearPanel(p, panel))
            {
                GetNearPanel(panel, sameList, sortedList);
            }
        }
        return sortedList;
    }

    private Boolean FindNearPanel(Panel p1, Panel p2)
    {
        SpriteRenderer render1 = p1.GetComponent<SpriteRenderer>();
        SpriteRenderer render2 = p2.GetComponent<SpriteRenderer>();

        CircleCollider2D co1 = p1.GetComponent<CircleCollider2D>();
        CircleCollider2D co2 = p2.GetComponent<CircleCollider2D>();

        //НЧСІ ЙќРЇ
        float a = co1.radius / 0.5f;
        float b = co2.radius / 0.5f;

        //РЬЙЬСіРЧ СпНЩСЁ
        Vector3 center1 = render1.bounds.center;
        Vector3 center2 = render2.bounds.center;

        //ХЉБтАЁ ДйИЅ ЦаГЮГЂИЎ ХНЛіАЁДЩЧЯАд МГСЄ
        return Vector3.Distance(center1, center2) < 1.3 * ((a + b) / 2f);
    }
}
